name: Build Windows Artifact
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip Files for Windows
        run: Compress-Archive -Path "index.html", "style.css" -DestinationPath "Onyachamp-Windows.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Onyachamp-Windows
          path: Onyachamp-Windows.zip
